<a href="https://colab.research.google.com/github/nikhithaaxreddy/NASSCOM/blob/main/panadas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data={"name":["A","B","C"],
"age":[20,18,22],
"marks":[10,20,30]}

In [ ]:
df= pd.DataFrame(data)

In [ ]:
print(df)

  name  age  marks
0    A   20     10
1    B   18     20
2    C   22     30

In [ ]:
df["marks"]

0    10
1    20
2    30
Name: marks, dtype: int64

In [ ]:
df.marks+5

0    15
1    25
2    35
Name: marks, dtype: int64

In [ ]:
df.head()

  name  age  marks
0    A   20     10
1    B   18     20
2    C   22     30

In [ ]:
df.shape

(3, 3)

In [ ]:
df.dtypes

name     object
age       int64
marks     int64
dtype: object

In [ ]:
df=pd.read_csv("/content/Student_Performance.csv")

In [ ]:
df.head()

,S.NO,Name,Roll NO,Branch,Hobby 1,Hobby 2,Place,no.of siblings,Age,Marks
0,1,Bhanu,25wh1a05,cse,dance,fun,nizampet,2,18,98
1,2,radha,25wh1a06,eee,singing,skating,rachapet,4,18,97
2,3,rani,25wh1a07,it,sliding,crafting,jntu,1,18,95
3,4,aju,25wh1a08,ece,writing,volley ball,rasulpura,3,18,96
4,5,kamal,25wh1a09,pharmacy,skating,cooking,paradaise circle,2,18,88

In [ ]:
df.dtypes

 S.NO              int64
Name              object
Roll NO           object
Branch            object
Hobby 1           object
Hobby 2           object
Place             object
no.of siblings     int64
Age                int64
Marks              int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    S.NO           25 non-null     int64
 1   Name            25 non-null     object
 2   Roll NO         25 non-null     object
 3   Branch          25 non-null     object
 4   Hobby 1         25 non-null     object
 5   Hobby 2         25 non-null     object
 6   Place           25 non-null     object
 7   no.of siblings  25 non-null     int64
 8   Age             25 non-null     int64
 9   Marks           25 non-null     int64
dtypes: int64(4), object(6)
memory usage: 2.1+ KB

In [ ]:
df["Marks"].median()

87.0

In [ ]:
df["Marks"].mean()
df["Marks"].std()
df["Marks"].min()
df["Marks"].max()
df["Marks"].quantile(0.25)
df["Marks"].quantile(0.50)
df["Marks"].quantile(0.75)

np.float64(90.0)

In [ ]:
df.describe

<bound method NDFrame.describe of      S.NO       Name   Roll NO    Branch  Hobby 1      Hobby 2  \
0       1      Bhanu  25wh1a05       cse    dance          fun
1       2      radha  25wh1a06       eee  singing      skating
2       3       rani  25wh1a07        it  sliding     crafting
3       4        aju  25wh1a08       ece  writing  volley ball
4       5      kamal  25wh1a09  pharmacy  skating      cooking
5       6      kumal  25wh1a10      mech   coding       living
6       7      kunal  25wh1a11        au    dance          fun
7       8    ravider  25wh1a12       cse  singing      skating
8       9       mani  25wh1a13       eee  sliding     crafting
9      10    ravider  25wh1a14        it  writing  volley ball
10     11       minu  25wh1a15       ece  skating      cooking
11     12    muickey  25wh1a16  pharmacy   coding       living
12     13      kumar  25wh1a17      mech    dance          fun
13     14     ramani  25wh1a18        au  singing      skating
14     15   nathvika  25wh1a19       cse  sliding     crafting
15     16     kumari  25wh1a20       eee  writing  volley ball
16     17    sahithi  25wh1a21        it  skating      cooking
17     18     sathya  25wh1a22       ece   coding       living
18     19  kanarvali  25wh1a23  pharmacy    dance          fun
19     20   kruthika  25wh1a24      mech  singing      skating
20     21      jadhu  25wh1a25        au  sliding     crafting
21     22     sumari  25wh1a26       cse  writing  volley ball
22     23     bonath  25wh1a27       eee  skating      cooking
23     24      kamal  25wh1a28      mech   coding       living
24     25      kamal  25wh1a29       eee   coding       living

               Place  no.of siblings  Age  Marks
0           nizampet               2   18     98
1           rachapet               4   18     97
2               jntu               1   18     95
3          rasulpura               3   18     96
4   paradaise circle               2   18     88
5           nalgonda               3   18     67
6          chiothhor               2   18     78
7            medchal               1   18     89
8       secunderabad               3   18     78
9          khafizpet               4   18     90
10        kuktapally               2   18     89
11               hyd               4   18     78
12         bachpally               5   18     67
13       lakdikapool               3   18     56
14          lb nagar               3   18     87
15       mehdipatnam               3   18      6
16          suchitra               4   18      9
17         malkampet               4   18     87
18          kondapur               2   18      7
19           chithur               1   18     98
20          erragada               3   18     67
21        iruumanzil               3   18      9
22        punjagutta               3   18     87
23          ameerpet               5   18      6
24          ameerpet               1   18     90  >